import type { StoryStructure } from "@/types"

export const storyStructures: StoryStructure[] = [
  {
    id: "hero-journey",
    name: "Hero's Journey",
    genre: "Fantasy/Adventure",
    description: "Classical 12-step hero journey structure",
    beats: [
      {
        id: "ordinary-world",
        name: "Ordinary World",
        description: "Show the hero's normal life before the adventure",
        percentagePosition: 5,
        requiredThreads: ["main"],
      },
      {
        id: "call-to-adventure",
        name: "Call to Adventure",
        description: "Present the main conflict or challenge",
        percentagePosition: 10,
        requiredThreads: ["main"],
      },
      {
        id: "refusal-call",
        name: "Refusal of the Call",
        description: "Hero initially resists the challenge",
        percentagePosition: 15,
        requiredThreads: ["main", "character-growth"],
      },
      {
        id: "meeting-mentor",
        name: "Meeting the Mentor",
        description: "Hero gets guidance for the journey ahead",
        percentagePosition: 20,
        requiredThreads: ["main", "character-growth"],
      },
      {
        id: "crossing-threshold",
        name: "Crossing the Threshold",
        description: "Hero commits to the adventure",
        percentagePosition: 25,
        requiredThreads: ["main"],
      },
      {
        id: "tests-allies-enemies",
        name: "Tests, Allies, and Enemies",
        description: "Hero faces challenges and builds relationships",
        percentagePosition: 40,
        requiredThreads: ["main", "character-growth"],
      },
      {
        id: "approach-innermost-cave",
        name: "Approach to the Innermost Cave",
        description: "Hero prepares for the major challenge",
        percentagePosition: 50,
        requiredThreads: ["main"],
      },
      {
        id: "ordeal",
        name: "The Ordeal",
        description: "Hero faces a major crisis",
        percentagePosition: 60,
        requiredThreads: ["main", "character-growth"],
      },
      {
        id: "reward",
        name: "The Reward",
        description: "Hero gains something needed to complete the journey",
        percentagePosition: 70,
        requiredThreads: ["main"],
      },
      {
        id: "road-back",
        name: "The Road Back",
        description: "Hero begins journey back to ordinary world",
        percentagePosition: 80,
        requiredThreads: ["main"],
      },
      {
        id: "resurrection",
        name: "The Resurrection",
        description: "Hero faces final test, demonstrating growth",
        percentagePosition: 90,
        requiredThreads: ["main", "character-growth"],
      },
      {
        id: "return-with-elixir",
        name: "Return with the Elixir",
        description: "Hero brings back something to benefit ordinary world",
        percentagePosition: 95,
        requiredThreads: ["main", "character-growth"],
      },
    ],
    commonThreads: [
      {
        name: "Main Quest",
        description: "The primary adventure or mission",
        color: "#FF0000",
        isMain: true,
      },
      {
        name: "Character Growth",
        description: "Hero's personal development arc",
        color: "#00FF00",
        isMain: false,
      },
    ],
  },
  {
    id: "romance",
    name: "Romance Arc",
    genre: "Romance",
    description: "Traditional romance story structure",
    beats: [
      {
        id: "meet-cute",
        name: "Meet Cute",
        description: "First encounter between love interests",
        percentagePosition: 10,
        requiredThreads: ["romance"],
      },
      {
        id: "resistance",
        name: "Resistance to Relationship",
        description: "Characters deny their attraction or face initial obstacles",
        percentagePosition: 20,
        requiredThreads: ["romance", "internal-conflict"],
      },
      {
        id: "first-kiss",
        name: "First Kiss/Connection",
        description: "First romantic moment or deepening connection",
        percentagePosition: 30,
        requiredThreads: ["romance"],
      },
      {
        id: "relationship-growth",
        name: "Relationship Development",
        description: "Couple grows closer despite challenges",
        percentagePosition: 45,
        requiredThreads: ["romance", "internal-conflict"],
      },
      {
        id: "midpoint-intimacy",
        name: "Midpoint Intimacy",
        description: "Significant deepening of relationship",
        percentagePosition: 50,
        requiredThreads: ["romance"],
      },
      {
        id: "complications",
        name: "Complications",
        description: "External/internal factors threaten relationship",
        percentagePosition: 65,
        requiredThreads: ["romance", "internal-conflict"],
      },
      {
        id: "black-moment",
        name: "Black Moment",
        description: "Couple separates or faces biggest challenge",
        percentagePosition: 80,
        requiredThreads: ["romance", "internal-conflict"],
      },
      {
        id: "resolution",
        name: "Resolution",
        description: "Couple overcomes final obstacles",
        percentagePosition: 90,
        requiredThreads: ["romance"],
      },
      {
        id: "happily-ever-after",
        name: "Happily Ever After",
        description: "Couple commits to lasting relationship",
        percentagePosition: 95,
        requiredThreads: ["romance"],
      },
    ],
    commonThreads: [
      {
        name: "Romance",
        description: "The main love story",
        color: "#FF69B4",
        isMain: true,
      },
      {
        name: "Internal Conflict",
        description: "Personal barriers to love",
        color: "#800080",
        isMain: false,
      },
    ],
  },
  {
    id: "supernatural-detective",
    name: "Supernatural Detective Mystery",
    genre: "Mystery/Supernatural",
    description: "Combines detective noir with supernatural elements",
    beats: [
      {
        id: "normal-case",
        name: "The Seemingly Normal Case",
        description: "Introduction of detective and initial mundane case",
        percentagePosition: 5,
        requiredThreads: ["investigation"],
      },
      {
        id: "supernatural-hint",
        name: "First Supernatural Element",
        description: "First hint that case involves supernatural forces",
        percentagePosition: 10,
        requiredThreads: ["investigation", "supernatural"],
      },
      {
        id: "initial-skepticism",
        name: "Skepticism and Denial",
        description: "Detective struggles to accept supernatural reality",
        percentagePosition: 15,
        requiredThreads: ["investigation", "character-growth"],
      },
      {
        id: "first-victim",
        name: "First Major Victim",
        description: "Case becomes serious with first major victim",
        percentagePosition: 20,
        requiredThreads: ["investigation"],
      },
      {
        id: "supernatural-confirmation",
        name: "Supernatural Confirmation",
        description: "Undeniable evidence of supernatural involvement",
        percentagePosition: 30,
        requiredThreads: ["investigation", "supernatural"],
      },
      {
        id: "investigation-deepens",
        name: "Investigation Deepens",
        description: "Detective learns rules of supernatural world",
        percentagePosition: 40,
        requiredThreads: ["investigation", "supernatural"],
      },
      {
        id: "personal-stakes",
        name: "Personal Stakes Revealed",
        description: "Case becomes personal for detective",
        percentagePosition: 50,
        requiredThreads: ["investigation", "character-growth"],
      },
      {
        id: "red-herrings",
        name: "Red Herrings",
        description: "False leads mixing mundane and supernatural",
        percentagePosition: 60,
        requiredThreads: ["investigation"],
      },
      {
        id: "major-revelation",
        name: "Major Revelation",
        description: "Key breakthrough in understanding the case",
        percentagePosition: 70,
        requiredThreads: ["investigation", "supernatural"],
      },
      {
        id: "preparation",
        name: "Preparation for Confrontation",
        description: "Detective gathers resources/allies for final confrontation",
        percentagePosition: 80,
        requiredThreads: ["investigation", "supernatural"],
      },
      {
        id: "climactic-confrontation",
        name: "Climactic Confrontation",
        description: "Face-off with supernatural antagonist",
        percentagePosition: 90,
        requiredThreads: ["investigation", "supernatural", "character-growth"],
      },
      {
        id: "resolution-consequences",
        name: "Resolution and Consequences",
        description: "Case solved but supernatural world forever changes detective",
        percentagePosition: 95,
        requiredThreads: ["investigation", "character-growth"],
      },
    ],
    commonThreads: [
      {
        name: "Investigation",
        description: "The main mystery/case",
        color: "#0000FF",
        isMain: true,
      },
      {
        name: "Supernatural",
        description: "Paranormal elements and revelations",
        color: "#800080",
        isMain: false,
      },
      {
        name: "Character Growth",
        description: "Detective's evolution in understanding supernatural world",
        color: "#008000",
        isMain: false,
      },
    ],
  },
  {
    id: "tech-supernatural-conspiracy",
    name: "Supernatural Tech Conspiracy Mystery",
    genre: "Urban Fantasy Detective",
    description: "Complex mystery involving supernatural beings, advanced technology, and interconnected subplots",
    beats: [
      {
        id: "initial-crime-scene",
        name: "Initial Crime Scene",
        description:
          "Detective (in disguise) processes an apparently mundane crime scene that will later prove significant",
        percentagePosition: 5,
        requiredThreads: ["main-investigation", "hidden-identity"],
      },
      {
        id: "status-change",
        name: "Status/Role Change",
        description: "Protagonist receives new position/authority that grants access to deeper investigation",
        percentagePosition: 10,
        requiredThreads: ["main-investigation"],
      },
      {
        id: "new-case-assignment",
        name: "New Case Assignment",
        description: "Assignment of seemingly unrelated case that will connect to larger conspiracy",
        percentagePosition: 15,
        requiredThreads: ["main-investigation", "tech-thread"],
      },
      {
        id: "first-supernatural-clue",
        name: "First Supernatural Connection",
        description: "Discovery of first clue linking case to supernatural community",
        percentagePosition: 20,
        requiredThreads: ["main-investigation", "supernatural-community"],
      },
      {
        id: "subplot-emergence-1",
        name: "First Subplot Emergence",
        description: "Introduction of first major subplot that will later provide crucial information",
        percentagePosition: 25,
        requiredThreads: ["subplot-thread-1"],
      },
      {
        id: "tech-discovery",
        name: "Technology Element Revealed",
        description: "Discovery of advanced organic technology involvement",
        percentagePosition: 30,
        requiredThreads: ["tech-thread", "main-investigation"],
      },
      {
        id: "identity-challenge",
        name: "Identity Challenge",
        description: "Situation that challenges protagonist's ability to maintain human disguise",
        percentagePosition: 35,
        requiredThreads: ["hidden-identity", "supernatural-community"],
      },
      {
        id: "subplot-emergence-2",
        name: "Second Subplot Emergence",
        description: "Introduction of another subplot thread with vital future connections",
        percentagePosition: 40,
        requiredThreads: ["subplot-thread-2"],
      },
      {
        id: "pattern-recognition",
        name: "Pattern Recognition",
        description: "First recognition of patterns connecting seemingly separate events",
        percentagePosition: 45,
        requiredThreads: ["main-investigation", "subplot-thread-1"],
      },
      {
        id: "supernatural-crisis",
        name: "Supernatural Community Crisis",
        description: "Major event affecting supernatural beings, raising stakes",
        percentagePosition: 50,
        requiredThreads: ["supernatural-community", "main-investigation"],
      },
      {
        id: "subplot-connection-1",
        name: "First Subplot Connection",
        description: "First subplot provides crucial information for main case",
        percentagePosition: 55,
        requiredThreads: ["main-investigation", "subplot-thread-1"],
      },
      {
        id: "tech-conspiracy",
        name: "Technology Conspiracy",
        description: "Discovery of how technology is being misused against supernatural beings",
        percentagePosition: 60,
        requiredThreads: ["tech-thread", "supernatural-community"],
      },
      {
        id: "subplot-emergence-3",
        name: "Third Subplot Emergence",
        description: "Final major subplot introduction",
        percentagePosition: 65,
        requiredThreads: ["subplot-thread-3"],
      },
      {
        id: "identity-decision",
        name: "Identity Crisis Decision",
        description: "Protagonist must decide whether to maintain or reveal true identity to solve case",
        percentagePosition: 70,
        requiredThreads: ["hidden-identity", "main-investigation"],
      },
      {
        id: "subplot-connections",
        name: "Subplot Convergence",
        description: "Multiple subplots begin revealing connections to main case",
        percentagePosition: 75,
        requiredThreads: ["subplot-thread-1", "subplot-thread-2", "subplot-thread-3"],
      },
      {
        id: "catalyst-revelation",
        name: "Catalyst Revelation",
        description: "Discovery of how initial crime scene connects everything",
        percentagePosition: 80,
        requiredThreads: ["main-investigation", "subplot-thread-1", "subplot-thread-2"],
      },
      {
        id: "conspiracy-exposed",
        name: "Conspiracy Exposed",
        description: "Full scope of tech-supernatural conspiracy revealed",
        percentagePosition: 85,
        requiredThreads: ["main-investigation", "tech-thread", "supernatural-community"],
      },
      {
        id: "final-confrontation",
        name: "Final Confrontation",
        description: "Confrontation with conspiracy masterminds",
        percentagePosition: 90,
        requiredThreads: ["main-investigation", "tech-thread", "supernatural-community"],
      },
      {
        id: "truth-revelation",
        name: "Truth Revelation",
        description: "Full truth revealed to key characters/public",
        percentagePosition: 95,
        requiredThreads: ["main-investigation", "hidden-identity"],
      },
      {
        id: "new-equilibrium",
        name: "New Equilibrium",
        description: "Resolution showing implications for both human and supernatural worlds",
        percentagePosition: 98,
        requiredThreads: ["main-investigation", "supernatural-community"],
      },
    ],
    commonThreads: [
      {
        name: "Main Investigation",
        description: "The primary case and its evolution",
        color: "#0000FF",
        isMain: true,
      },
      {
        name: "Hidden Identity",
        description: "Protagonist's concealment and challenges of their true nature",
        color: "#800080",
        isMain: false,
      },
      {
        name: "Tech Thread",
        description: "Advanced organic technology aspects of the case",
        color: "#00FF00",
        isMain: false,
      },
      {
        name: "Supernatural Community",
        description: "Issues affecting supernatural beings and their world",
        color: "#FF4500",
        isMain: false,
      },
      {
        name: "Subplot Thread 1",
        description: "First major subplot line",
        color: "#FFD700",
        isMain: false,
      },
      {
        name: "Subplot Thread 2",
        description: "Second major subplot line",
        color: "#FF69B4",
        isMain: false,
      },
      {
        name: "Subplot Thread 3",
        description: "Third major subplot line",
        color: "#20B2AA",
        isMain: false,
      },
    ],
  },
]

